language: php
sudo: false

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

php:
  - '7.0'
  - '7.1'
  - nightly

install:
  - travis_retry composer update

script: ./vendor/bin/phpunit
