language: php
sudo: false

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

install:
  - travis_retry composer install

script: ./vendor/bin/phpunit --configuration phpunit.xml.dist
