language: php
sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache


matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: nightly
      env: COMPOSER_FLAGS="--ignore-platform-reqs"
  allow_failures:
    - php: 7.0
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: nightly

install:
  - travis_retry composer update

script: ./vendor/bin/phpunit
